### ISSUE TITLE
python3 start.py 报错

### ISSUE THREAD

**Issue by pchychan** [NolanGit/PersonalHomepage#20]
求大佬！
Exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/idna-2.10.dist-info/INSTALLER' -> '/tmp/pip-khqp30f6-uninstall/usr/local/lib/python3.6/site-packages/idna-2.10.dist-info/INSTALLER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 783, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib64/python3.6/shutil.py", line 565, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/idna-2.10.dist-info/INSTALLER'

**Comment by NolanGit** [comment]
> 求大佬！
> python3 start.py走完后，打不开页面

hi，附一下控制台报错或者更详细的信息吧，我来帮你排查一下
